config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/homes', to: 'home#index'
  resources :auction_items, only: [:show]
  resources :bids, only: [:create, :update]
  resources :admin, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  has_many :auction_items
end

app/models/auction_item.rb
class AuctionItem < ApplicationRecord
  has_many :item_attachments
  has_many :bids
  belongs_to :user
  belongs_to :auction
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction_item

  def approve
    bids =  auction_item.bids
    bids.where.not(id: self.id).update_all(status: 'rejected')
    update(status: 'approved')
    auction_item.update(current_bid_amount: bid_amount)
  end
end

app/models/item_attachment.rb
class ItemAttachment < ApplicationRecord
  belongs_to :auction_item
end

app/models/user.rb
class User < ApplicationRecord
  has_many :auction_items
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  include HttpAuthConcern

  def index
    @auctions = Auction.where("starts_at < ?",Time.current).where("ends_at > ?", Time.current)
    @auction_items = AuctionItem.where(auction_id: @auctions.pluck(:id)).where(is_bid_allowed: true).includes(:bids).all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auction_items_controller.rb
class AuctionItemsController < ApplicationController

  def show
    @auction_item = AuctionItem.where(id: params[:id]).first

    return redirect_to root_path if Time.now > @auction_item.auction.ends_at
    
    @bid = @auction_item.bids.build
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  def create
    Bid.create(bid_params)
    redirect_to root_path
  end

  def update
    bid = Bid.where(id: params[:id]).first
    if bid && params[:bid][:status] == 'approved'
      bid.approve
    end
    redirect_to admin_index_path
  end

  private

  def bid_params
    params.require(:bid).permit(:name, :mobile, :bid_amount, :auction_item_id)
  end
end

app/controllers/concerns/http_auth_concern.rb
module HttpAuthConcern  
  extend ActiveSupport::Concern
  included do
    before_action :http_authenticate
  end

  def http_authenticate
    return true unless Rails.env == 'production'
    authenticate_or_request_with_http_basic do |username, password|
      username == Rails.application.credentials.username && password == Rails.application.credentials.password
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @auctions = Auction.where("starts_at < ?",Time.current).where("ends_at > ?", Time.current)
    @auction_items = AuctionItem.where(auction_id: @auctions.pluck(:id)).where(is_bid_allowed: true)
    @non_auction_items = AuctionItem.where(auction_id: @auctions.pluck(:id)).where(is_bid_allowed: false)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/index.haml
%section.mt-4.pt-4
%section.mt-4.pt-4
%section.mt-2.pt-2
%div
  .container
    - @auction_items.each do |auction_item|
      .row
        .single-product-content.col-lg-5.col-12.mb-30
          / Title
          %h1.title #{auction_item.name}
          %span.product-price  ₹ #{auction_item.current_bid_amount}
          / Description
          .description
            - bids = auction_item.bids
            %p Total bids: #{bids.length}

            - bid = bids.filter{|bid| bid.status == 'approved'}.sort_by{|bid| bid.bid_amount}.last
            - if bid
              %p Current Owner
              = bid.name
              = bid.mobile
              = bid.bid_amount
          / Color
          .product-color.fix
            - bids.sort_by{|bid| bid.bid_amount}.reverse.each do |bid|
              = bootstrap_form_for(bid) do |f|
                = bid.name
                = bid.mobile
                = bid.bid_amount
                = f.hidden_field :status, value: 'approved'
                - if bid.status == nil
                  = f.submit "Approve"

app/views/auction_items/show.haml
%section.mt-4.pt-4
%section.mt-4.pt-4
%section.mt-2.pt-2
%div
  .container
    .row
      .single-product-content.col-lg-5.col-12.mb-30
        / Title
        %h1.title #{@auction_item.name}
        %span.product-price  ₹ #{@auction_item.current_bid_amount}
        / Description
        .description
          %p
        / Color
        .product-share.fix
          Note: Highest bid will be updated every 1 hour, check back after 1 hour for latest price of product
        .product-color.fix
          %h5 Enter details
          = bootstrap_form_for(@bid) do |f|
            = f.hidden_field :auction_item_id, value: @auction_item.id
            = f.text_field :name, required: true, label: 'Name'
            = f.telephone_field :mobile, required: true, minlength: 10
            = f.number_field :bid_amount, min: @auction_item.current_bid_amount + 100, required: true
            = f.submit "Add your bid"

        / Action Button
        .product-action-button.fix
          -# %button
          -#   %i.ion-ios-email-outline>
          -#   Email to a friend
          -# %button
          -#   %i.ion-ios-heart-outline>
          -#   Wishlist
          -# %button
          -#   %i.ion-ios-printer-outline>
          -#   Print
        / Social Share
        .product-share.fix
          %button
            = link_to 'Back', root_path
          -# %h6 Share :
          -# %a{:href => "#"}
          -#   %i.fa.fa-facebook
          -# %a{:href => "#"}
          -#   %i.fa.fa-twitter
          -# %a{:href => "#"}
          -#   %i.fa.fa-instagram
          -# %a{:href => "#"}
          -#   %i.fa.fa-pinterest-p

app/views/home/index.haml
%section.mt-4.pt-4
%section.mt-4.pt-4
%section.mt-2.pt-2
.box
  =image_tag('banner.png')
%div
  .container
    .row
      .section-title.text-center.col.mb-60.pt-10
        %h1 Auctiond Items
    .row.row-cols-3
      - @auction_items.each do |item|
        - bid = item.bids.filter{|bid| bid.status == 'approved'}.sort_by{|bid| bid.bid_amount}.last
        .col-sm-4.mt-2
          .product
            .image
              %a.img
                %img.zoom{alt: "Product", src: item.image_url}/
            .content.p-4
              .head.fix
                .title-category.float-left
                  %h5.title
                    %a #{item.name}
                  .div
                    %a #{item.description}
                  %a #{item.user.name}
                .price.float-right
                  %span.new ₹ #{item.current_bid_amount}
                  - if bid
                    .div
                      - if Time.now < item.auction.ends_at
                        %a Current Owner: #{bid.name}
                      -else
                        %a Sold to: #{bid.name}
              - if Time.now < item.auction.ends_at
                .action-button.fix
                  = link_to 'Add your bid', auction_item_path(item.id)

  %div
    .container
      .row
      .section-title.text-center.col.mb-60.pt-10
        %h1 Non Auctiond Items
        .row.text-center.font-italic
          %h6 For these items contact Admin directly 
    .row.row-cols-3
      - @non_auction_items.each do |item|
        .col-sm-4.mt-2
          .product
            .image
              %a.img
                %img.zoom{alt: "Product", src: item.image_url}/
            .content.p-4
              .head.fix
                .title-category.float-left
                  %h5.title
                    %a #{item.name}
                  .div
                    %a #{item.description}
                  %a #{item.user.name}
                .price.float-right
                  %span.new ₹ #{item.current_bid_amount}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"}/
    %meta{:name => "google", :value => "notranslate"}/
    %title We Care
    = favicon_link_tag image_path('logo')
    / begin::Fonts
    -# %script{:src => "https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"}
    -# :javascript
    -#   WebFont.load({
    -#     google: {"families":["Poppins:300,400,500,600,700","Raleway:300,400,500,600,700"]},
    -#       active: function() {
    -#         sessionStorage.fonts = true;
    -#       }
    -#     });
    / end::Fonts

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    -# = stylesheet_link_tag "internal/#{params[:controller]}"
    = yield :stylesheet if content_for?(:stylesheet)
    = csrf_meta_tags
    = csp_meta_tag
    -# = favicon_link_tag 'favicon.ico'
    -# = favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon', type: 'image/png', skip_pipeline: true
  / begin:: Body
  %body
    / begin:: Page
    .fb-page-wrapper
      = render "partial/header"
      .fb-content-wrapper
        .fb-content
          =yield
        = render "partial/footer"
    - unless flash.empty?
      %script
        - flash.each do |f|
          - type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info')
          toastr['#{type}']('#{f[1]}');
        - flash.clear
    / end:: Page
    = yield :beforeBodyEnd if content_for?(:beforeBodyEnd)
    / end::Global Config
    :javascript
      //inline js
      $(document).on("click", function(e) {
        if (($(e.target).is(".modal-backdrop, .logo, .logo *") === true)) {
          $ (".modal").modal ("hide");
        }
      });
    = yield :javascript if content_for?(:javascript)
    -# = javascript_include_tag "bs_theme/bs_"+params[:controller]
    %script
      -# webslidemenu.onLoad(); // global js
  / end:: Body

app/views/partial/_card.haml
.col-lg-4.col-md-6.col-12.mb-60
  .product
    .image
      %a.img
        %img{alt: "Product", src: "https://www.primopt.com/wp-content/uploads/2018/04/Home-Four-Banner-Background-Image-1.png"}/
      %a.wishlist{href: "#"}
        %i.fa.fa-heart-o
      %span.label New
    .content
      .head.fix
        .title-category.float-left
          %h5.title
            %a{href: "product-details.html"} Holiday Candle
          %a.category{href: "shop.html"} Catalog
        .price.float-right
          %span.new $38
      .action-button.fix
        %a{href: "#"} add to cart

app/views/partial/_footer.haml
.footer-section.section.bg-dark{:style => "background-image: url(img/bg/footer-bg.png)"}
  .container
    .row
      .col
        / Footer Top Start
        .footer-top.section.pt-30.pb-40
          .row
            / Footer Widget
            .footer-widget.col-sm-6
              %h3 Josh Software
              %p Josh stands for enthusiasm and passion. We believe Programming is an Art and build Innovative Web Based Applications on an Open Source framework for our world-wide clientele.

            .footer-widget.col-sm-6
              .row.d-flex.float-end
                .col
                  %a{:href => "https://www.facebook.com/joshsoftware", :target => "_blank"}
                    %i.fab.fa-facebook.fa-2x
                .col
                  %a{:href => "https://twitter.com/joshsoftware", :target => "_blank"}
                    %i.fab.fa-twitter.fa-2x
                .col
                  %a{:href => "http://www.linkedin.com/company/josh-software-private-limited", :target => "_blank"}
                    %i.fab.fa-linkedin.fa-2x
                .col
                  %a{:href => "https://www.instagram.com/josh.software/", :target => "_blank"}
                    %i.fab.fa-instagram.fa-2x

app/views/partial/_header.haml
%header.fb-page-header
  .header-section.section
    .row
      .col
        .header-top-wrapper
          .header.logo.row
            %a.col.m-2
              =image_tag('logo.png', style:"width: 170px")
            %a.col.m-2
              =image_tag('josh-logo.svg', style:"width: 170px", class:"float-end")

app/views/partial/_product_list.haml
.product-section.section.pt-70.pb-60
  .container
    .row
      .section-title.text-center.col.mb-60
        %h1 Featured Products
    .row
      = render "partial/card"
      = render "partial/card"
      = render "partial/card"